<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Register Account</title>
</head>
<body bgcolor="#FA8072">
	<h1 align="center">Register Account</h1>
	<div align="center">
		<form action="Registration" method="">
			<p>User Name:</p> <input type="text" name="UName" size="30" ><br><br>
			<p>E-mail:</p> <input type="email" name="email" size="30" ><br><br>
			<p>Password:</p> <input type="password" name="Upassword" size="30" ><br><br>
			<input type="submit" value="Register">
			<a href="Login.jsp">Already have an account?</a>
		</form>
	
	</div>



</body>
</html>